services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
#      - xpack.security.enabled=true
#      - ELASTIC_PASSWORD=wayble_2025
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.2
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      #- ELASTICSEARCH_USERNAME=elastic
      #- ELASTICSEARCH_PASSWORD=wayble_2025      # Kibana에서 ES 접속용 비밀번호
      #- ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/ca.crt  # SSL 쓸 경우
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - es-network

networks:
  es-network:
    driver: bridge

volumes:
  esdata:
    driver: local