services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
#      - xpack.security.enabled=true
#      - ELASTIC_PASSWORD=<PASSWORD>
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es-network

networks:
  es-network:
    driver: bridge

volumes:
  esdata:
    driver: local

# docker compose -f docker-els.yml up -d